---
name: increment-release-version

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  increment-release-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - run: echo "CURRENT_MAJOR_VERSION=$(grep tag_name .github/workflows/create-release.yml | sed -e 's/.*\(v[0-9]*\.[0-9]*\)\..*/\1/g')" >> "${GITHUB_ENV}"
      - name: Get latest release version
        id: get_latest_release_version
        uses: actions/github-script@v6.1.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            try {
              return (await github.rest.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo
              })).data.tag_name;
            } catch (e) {
              if (e instanceof HttpError && e.status === 404) {
                return 'v0.0.0';
              }

              throw e;
            }
      - name: Increment version
        id: increment_version
        if: startsWith(steps.get_latest_release_version.outputs.result, env.CURRENT_MAJOR_VERSION)
        uses: actions/github-script@v6.1.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const tagNames = '${{ steps.get_latest_release_version.outputs.result }}'.split('.');
            return [tagNames[0], tagNames[1], Number(tagNames[2]) + 1].join('.');
      - if: startsWith(steps.get_latest_release_version.outputs.result, env.CURRENT_MAJOR_VERSION)
        run: sed -i -e 's/tag_name:\ \'v[0-9.]*/tag_name:\ \'${{ steps.increment_version.outputs.result }}/g' .github/workflows/create-release.yml
      - uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-name-prefix: increment-release-version
          pr-title-prefix: リリースバージョンをインクリメントしてあげたよ！
          repo-name: ${{ github.event.pull_request.head.repo.full_name }}
