---
name: renovate_config_validator

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3.5.1
        with:
          cache: npm
      - run: ./scripts/npm_ci.sh
      - run: ./scripts/renovate_config_validator/run_renovate_config_validator.sh
