---
name: test

on:
  push:
    branches:
      - add_push_trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-name-prefix: fix-readme-test
          pr-title-prefix: README修正 (test)
          pr-description-prefix: READMEを修正しました。

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
