---
name: update-dist
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  update-dist:
    # jscpd:ignore-start
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          cache: npm
          node-version-file: .node-version
      # jscpd:ignore-end
      - if: github.event_name != 'pull_request' || github.event.action != 'closed'
        run: npm ci
      - if: github.event_name != 'pull_request' || github.event.action != 'closed'
        run: tsc --outDir dist/ scripts/action/*.ts
      - uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-name-prefix: apply-to-dist
          pr-title-prefix: dist反映
          pr-description-prefix: "`scripts/action` 以下のTypeScriptを `dist` 以下にJavaScriptとして反映します。"
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
