---
name: update-dist
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  update-dist:
    # jscpd:ignore-start
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - if: github.event_name != 'pull_request' || github.event.action != 'closed'
        run: bash "${GITHUB_WORKSPACE}/scripts/update_dist/update_dist/update_dist.sh"
      - uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-name-prefix: apply-to-dist
          pr-title-prefix: dist反映
          pr-description-prefix: "`scripts/action` 以下のTypeScriptを `dist` 以下にJavaScriptとして反映します。"
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
